add eslint and prettier
SMB-production/dish-balance-front pull request #3
Opened 2024-11-01 22:33 UTC by nnnikserrrr

2024-11-02 04:38 UTC, Gribanov-Danil commented on .prettierrc.json
> +   "jsxSingleQuote": false,
Давай заменим на true

2024-11-02 04:39 UTC, Gribanov-Danil requested changes
Связать форматирование линтером с пре-коммитом

2024-11-03 07:37 UTC, nnnikserrrr commented on .prettierrc.json
> +   "jsxSingleQuote": false,
почему "semi": "true"?

2024-11-03 09:26 UTC, Gribanov-Danil commented on .prettierrc.json
> +   "jsxSingleQuote": false,
Код ощущается менее слипшимся

2024-11-03 09:35 UTC, Gribanov-Danil requested changes
Связать с пре-коммитом. В этой ветке нет актуальных изменения с хаски. Для этого необходимо сделать ребейз ветки мейн (можно мерж, но лучше ребейз, чтобы история была стройнее)
![image](https://github.com/user-attachments/assets/2536d896-b672-4bf1-a1ed-ba4369f81b9c)

Далее необходимо решить конфликты слияния в файлах package.json и package-lock.json. Конфликт в package-lock.json можно решить не запариваясь, после решения необходимо удалить этот файл и папку нод модулей и сделать заново npm i. Это не хорошая практика, но на таком проекте это не критично

2024-11-03 09:35 UTC, Gribanov-Danil commented on .prettierrc.json
> +   "bracketSpacing": false,
Заменить на true

2024-11-03 09:35 UTC, Gribanov-Danil commented on package.json
> +   },
Это надо связать с пре-коммитом

2024-11-04 05:38 UTC, Gribanov-Danil requested changes

2024-11-04 05:38 UTC, Gribanov-Danil commented on package.json
> +			"eslint"
Дублирование логики. Можно через регулярное выражение объединить команды для js\ts в один блок. Также команда "git add" не особо нужна

2024-11-04 06:32 UTC, Gribanov-Danil approved these changes

2024-11-04 06:34 UTC, merged